#!/bin/bash

set -e
set -o pipefail
source /usr/local/share/helper_functions.sh

function report_ssl_vars() {
    report_vars SSL_CERT_MODE SSL_CERT_NAME SSL_CERT_PATH SSL_CERT_PEMFILE SSL_CERT_KEYFILE
    if [ "$SSL_CERT_MODE" != "snakeoil" ]; then 
        report_vars CERTBOT_WEBROOT
    fi
}

[ "$SSL_CERT_MODE" = "snakeoil" ] || [ "$SSL_CERT_MODE" = "prod" ] || export SSL_CERT_MODE=staging
export SSL_CERT_MODE

if [ "$SSL_CERT_MODE" = "snakeoil" ]; then
    export SSL_CERT_NAME=snakeoil
    export SSL_CERT_PATH=/etc/nginx/ssl/$SSL_CERT_NAME
else
    export SSL_CERT_NAME=${SSL_CERT_MODE}
    export SSL_CERT_PATH=/etc/letsencrypt/live/$SSL_CERT_NAME
    export CERTBOT_WEBROOT=/var/lib/letsencrypt/challenges
fi

export SSL_CERT_PEMFILE=$SSL_CERT_PATH/fullchain.pem
export SSL_CERT_KEYFILE=$SSL_CERT_PATH/privkey.pem

if [ "$(basename $0)" = "determine_cert_paths" ]; then
   report_ssl_vars
fi
