#!/bin/bash

set -e 
set -o pipefail

source /usr/local/share/helper_functions.sh
	
mkdir -p /etc/nginx/ssl
if [ ! -e /etc/nginx/ssl/dhparam.pem ]; then
  say "dpharam is missing, generating it (may take time)"
  openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048 #4096
  say "dhparam generated"
else
  say "dhparam is already in place, not regenerating it"
fi
